[package]
name = "oxify-derive"
version = "0.1.0"
edition = "2021"
authors = ["Carlos Tocino <carlostocinocubelo@gmail.com>"]
description = "Oxify's derive macro crate"

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.87"

[lib]
proc-macro = true
