[package]
name = "oxify"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
crossterm = "0.28.1"
dotenvy = "0.15.7"
rand = "0.8.5"
ratatui = "0.28.1"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
