[package]
name = "oxify"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
derive_setters = "0.1.6"
dotenvy = "0.15.7"
log = "0.4.22"
open = "5.3.0"
rand = "0.8.5"
ratatui = "0.28.1"
simplelog = "0.12.2"
ureq = "2.10.1"
