[package]
name = "oxify"
version = "0.0.1-dev"
edition = "2021"
authors = ["Carlos Tocino <carlostocinocubelo@gmail.com>"]
description = "Lightweight, customizable Spotify client"
rust-version = "1.84.0"
readme = "README.md"
homepage = "https://oxify.rs"
license = "MIT"
repository = "https://github.com/sharlibeicon/oxify"

[[bin]]
name = "oxify"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
iced = "0.13.1"
librespot = { git="https://github.com/SharliBeicon/librespot.git", rev="0.6.0-oxify" }
log = "0.4.25"
simplelog = "0.12.2"

[profile.dev]
opt-level = 0

[profile.release]
panic = "abort"
opt-level = 3
lto = true
strip = true
