[package]
name = "oxify"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
crossterm = "0.28.1"
derive_setters = "0.1.6"
log = "0.4.22"
open = "5.3.0"
rand = "0.8.5"
ratatui = "0.28.1"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
simplelog = "0.12.2"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
