[package]
name = "oxify"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
crossterm = "0.28.1"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["rt"] }
