[package]
name = "oxify"
version = "0.1.0"
edition = "2021"
authors = ["Carlos Tocino <carlostocinocubelo@gmail.com>"]
description = "A TUI Spotify Client"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
crossterm = "0.28.1"
derive_setters = "0.1.6"
log = "0.4.22"
open = "5.3.0"
rand = "0.8.5"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
simplelog = "0.12.2"
ureq = "2.10.1"
librespot-core = "0.5.0"
librespot-playback = "0.5.0"
librespot-protocol = "0.5.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
